spring:
  datasource:
    url: jdbc:postgresql://c-c9q7areu6cghj0sacco8.rw.mdb.yandexcloud.net:6432/cashback
    username: lena
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: create-drop
